import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import {useAuth} from "../context/AuthContext";
// import {reshrdMailer} from "../infrastructure/email-service";
import Mail from "nodemailer/lib/mailer";

export default function Contact() {
    const {currentUser} = useAuth();
    const [email, setEmail] = useState(currentUser?.email || "");
    const [message, setMessage] = useState("");


    const handleSubmit = async (e: any) => {
        e.preventDefault();

        const emailConfig: Mail.Options = {
            subject: "Qr id contact form",
            to: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'qwercy142@gmail.com',
            from: email,
            sender: 'Qr id contact form',
            text: message,
        };



        try {
            // await reshrdMailer.send(emailConfig);
            console.log(
                'sending email is not implemented yet',
            )
            setMessage("");
            setEmail("");

        } catch (e) {

        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Qr id | Contact</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Contact us
                </h1>

                <div>

                    <form>
                        <div>
                            <label htmlFor="email">Email</label>
                            <input type="email" name="email" id="email" value={email}
                                   onChange={(e) => setEmail(e.target.value)}/>

                            <br/>

                            <label htmlFor="message">Message</label>
                            <textarea name="message" id="message" cols={30} rows={10} value={message}
                                      onChange={(e) => setMessage(e.target.value)}/>

                        </div>

                        <button type="submit" onClick={handleSubmit}>Send</button>

                    </form>


                </div>

            </main>
        </div>
    )
}
