import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {useAuth} from "../context/AuthContext";

export default function Home() {
    const {currentUser} = useAuth();

    console.log(currentUser);

  return (
    <div className={styles.container}>
      <Head>
        <title>Qr id | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to QR ID
        </h1>

        <p className={styles.description}>
          Get yourself changeable QR code clothing that can be updated at any time.
        </p>

        <div className={styles.grid}>
          <Link href="/items" className={styles.card}>
            <h2>Manage your items &rarr;</h2>
            <p>
                Here you can manage your items!
            </p>
          </Link>

          <Link href="/about" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>
                Learn more about QR ID.
            </p>
          </Link>

        </div>
      </main>
    </div>
  )
}
