import styles from "../styles/Home.module.css";
import Head from "next/head";
import {ProtectedRoute} from "../components/ProtectedRoute/ProtectedRoute";

export default function Items() {
    return (
        <ProtectedRoute type={'onlyAuth'}>
            <div className={styles.container}>
                <Head>
                    <title>Qr id | Your items</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Your items
                    </h1>

                    <p className={styles.description}>
                        Here you can see all your items
                    </p>

                </main>

            </div>
        </ProtectedRoute>
    );
}