import Head from "next/head";
import styles from '../styles/Home.module.css'
import {useState} from "react";
import Link from "next/link";
import {useAuth} from "../context/AuthContext";
import {useRouter} from "next/navigation";
import {ProtectedRoute} from "../components/ProtectedRoute/ProtectedRoute";


export default function Register() {

    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [password2, setPassword2] = useState("");
    const [error, setError] = useState("");

    const {register} = useAuth();
    const router = useRouter();

    const handleRegister = async (e: any) => {
        e.preventDefault();
        setError("");

        try {
            await register(email, password);
            router.push('/');

        } catch (e) {
            console.log(e);
            setError('Failed to create an account, please try again or contact support');
        }

    };
    return (
        <ProtectedRoute type={'onlyGuest'}>

            <div className={styles.container}>
                <Head>
                    <title>Qr id | Register</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>

                    <div>

                        <h3>Register</h3>

                        <form>
                            <div>
                                <label htmlFor="email">Email</label>
                                <input type="email" name="email" id="email" onChange={(e) => setEmail(e.target.value)}/>

                                <br/>
                                <label htmlFor="password">Password</label>
                                <input type="password" name="password" id="password"
                                       onChange={(e) => setPassword(e.target.value)}/>

                                <br/>
                                <label htmlFor="password2">Confirm password</label>
                                <input type="password" name="password2" id="password2"
                                       onChange={(e) => setPassword2(e.target.value)}/>

                            </div>

                            <button type="submit" onClick={handleRegister}>Register</button>

                        </form>


                        <p>
                            Already have an account? <Link href={"/login"}>Login</Link>

                        </p>
                    </div>

                </main>


            </div>
        </ProtectedRoute>
    );
}